export const SET_LOADING = "SET_LOADING";

export const QUERY_POKEMON = "QUERY_POKEMON";

export const GET_POKEMON_LIST = "GET_POKEMON_LIST";
export const FETCH_FORM_LIST = "FETCH_FORM_LIST";

export const POKEMON_ERROR = "POKEMON_ERROR";
